# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25850c2257fc203250e6595cdfea97eddabd34e3a781957855e66d5191916ea4288bc661dfaf22948109c68aed0431f35a2cc5fc6f323644b103e84099b16e62

test:
  secret_key_base: 1c63c5e94a3aa9d95c92a49abba5160a025f223dd613dec83a03d81281fd50d8aa63b8c51044f9fe1eb6cf2e3f1a08e074e92cf3ba3ab4c2ce2616c030feea36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging:
  secret_key_base: 25850c2257fc203250e6595cdfea97eddabd34e3a781957855e66d5191916ea4288bc661dfaf22948109c68aed0431f35a2cc5fc6f323644b103e84099b16e62

production:
  secret_key_base: 25850c2257fc203250e6595cdfea97eddabd34e3a781957855e66d5191916ea4288bc661dfaf22948109c68aed0431f35a2cc5fc6f323644b103e84099b16e62
#secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
